### ISSUE TITLE
Why use .include and not .eql for string matching?

### ISSUE THREAD

**Issue by andbroby** [jsomers/git-game#13]
I'm probably missing something, but why not use `.eql` when matching the guess and the author name at [git-game:L95](https://github.com/jsomers/git-game/blob/master/git-game#L95)?

With `.include`, guess `a`  would match author `Andreas Broby`. Is that intended behaviour? I've made a pull request just in case it's not.

**Comment by Epigene** [comment]
author.downcase.include?(guess.strip.downcase) does indeed allow matching an author "Andreas Broby" to a guess of "a".

This poses a big problem is all committers share a letter in their handles ("e", "a" and "o" common http://en.wikipedia.org/wiki/Letter_frequency)

The guess should be enforced at 3 letters minimum as the chance of trigrams overlapping is significantly reduced compared to a single letter.

**Comment by andbroby** [comment]
Exactly. Forcing trigrams is not a bad solution if you were to continue using `include` (which I guess makes sense if you're playing in a repo  where you can't remember the exact name of every contributor). It would complicate things a bit though, since you'd have to take care of cases where usernames are shorter than 3 characters.

The script could use `eql` in combination with something like [Ruby's interface to GNU Readline](http://ruby-doc.org//stdlib-1.9.3/libdoc/readline/rdoc/Readline.html) for username autocompletion, but then you'd have to take different systems into account. Blah. :stuck_out_tongue:

**Comment by jsomers** [comment]
@andbroby @Epigene My thought was that the `include?` solution allows you to (a) type answers more quickly and (b) worry less about spelling / getting someone's full exact name correctly. This is what I also do in [Jimbo Jeopardy](https://github.com/jsomers/j-jeopardy). I figured it would be on the player's honor not to type, say, the letter "a", but rather to try to type as much of the name as they think will select it unambiguously.

I see where you're coming from, but I favor the multiple-choice solution to something that requires you to type someone's name exactly (which seems tedious). So I'm going to close https://github.com/jsomers/git-game/pull/14 (though I appreciate the pull) and probably switch to using a multiple-choice format instead. Thanks!
