### ISSUE TITLE
Respect .mailmap

### ISSUE THREAD

**Issue by jeffreylo** [jsomers/git-game#31]
My co-worker doesn't know how to `git config user.name`, so I've got triple entries for the same person. It really ruins the game.

https://stacktoheap.com/blog/2013/01/06/using-mailmap-to-fix-authors-list-in-git/

**Comment by jeffreylo** [comment]
pls

**Comment by jsomers** [comment]
@jeffreylo i will accept a pull request!

**Comment by jeffreylo** [comment]
will do! thank ye kindly, BDFL of `git-game`, the greatest game in the world
