### ISSUE TITLE
Commit message to guess shows just a "%B"

### ISSUE THREAD

**Issue by amitlan** [jsomers/git-game#9]
Trying this out in postgres.git and $SUBJECT happens as follows:

(12 years ago)
%B

Who wrote it (current streak: 0)?

**Comment by amitlan** [comment]
I see in man git-log that %B is not supported in my version of git (1.7.1).

```
<snip>
·    %b: body

·    %N: commit notes
<snip>
```

**Comment by jsomers** [comment]
@amitlan ahh, got it -- well I don't know if there's any harm in upgrading git! I'm going to close this one, thanks
